// import type { Metadata } from "next";
// import { Montserrat, Cormorant_Garamond } from "next/font/google";
// import "./globals.css";

// const montserrat = Montserrat({
//   variable: "--font-montserrat",
//   subsets: ["latin"],
//   weight: ["400", "600", "700"],
// });

// const cormorant = Cormorant_Garamond({
//   variable: "--font-cormorant",
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700"],
//   style: ["normal", "italic"],
// });

// export const metadata: Metadata = {
//   title: "Дизайн интерьера",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="ru">
//       <body
//         className={`${montserrat.variable} ${cormorant.variable} antialiased`}
//       >
//         <main className="min-h-screen">{children}</main>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Montserrat, Cormorant_Garamond } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin", "cyrillic"], // Добавили кириллицу
  weight: ["400", "600", "700"],
});

const cormorant = Cormorant_Garamond({
  variable: "--font-cormorant",
  subsets: ["latin", "cyrillic"],
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: {
    default: "Дизайн интерьера | Студия [Имя Фамилия]",
    template: "%s | Студия дизайна [Имя]"
  },
  description: "Авторские дизайн-проекты интерьеров под ключ. Создаю эстетичные и функциональные пространства в [городах]. 10+ лет опыта.",
  keywords: [
    "дизайн интерьера",
    "дизайнер интерьеров [город]",
    "ремонт под ключ",
    "авторский надзор",
    "дизайн-проект",
    "интерьер жилых помещений",
    "коммерческие интерьеры"
  ],
  authors: [{ name: "[Имя Фамилия]", url: "https://вашсайт.ru" }],
  openGraph: {
    title: "Дизайн интерьера | [Имя Фамилия]",
    description: "Эксклюзивные интерьерные решения от профессионального дизайнера",
    url: "https://вашсайт.ru",
    siteName: "Студия дизайна [Имя]",
    images: [
      {
        url: "https://вашсайт.ru/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Пример работы дизайнера"
      }
    ],
    locale: "ru_RU",
    type: "website"
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1
    }
  },
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
  manifest: "/site.webmanifest",
  metadataBase: new URL("https://вашсайт.ru"),
  alternates: {
    canonical: "/",
    languages: {
      "ru-RU": "/ru",
    },
  },
  verification: {
    google: "ваш-google-verification-code",
    yandex: "ваш-yandex-verification-code"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className="scroll-smooth">
      <head>
        {/* Скрипты для веб-аналитики */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'GA_MEASUREMENT_ID');
            `,
          }}
        />
      </head>
      <body className={`${montserrat.variable} ${cormorant.variable} antialiased`}>
        {/* Schema.org разметка */}
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "ProfessionalService",
            "name": "Студия дизайна [Имя]",
            "image": "https://вашсайт.ru/logo.jpg",
            "@id": "https://вашсайт.ru",
            "url": "https://вашсайт.ru",
            "telephone": "+7 (XXX) XXX-XX-XX",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "ул. Примерная, 123",
              "addressLocality": "[Город]",
              "postalCode": "123456",
              "addressCountry": "RU"
            },
            "geo": {
              "@type": "GeoCoordinates",
              "latitude": "55.755825",
              "longitude": "37.617298"
            },
            "openingHoursSpecification": {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
              "opens": "10:00",
              "closes": "19:00"
            },
            "priceRange": "$$$"
          })}
        </script>

        <main className="min-h-screen">
          {children}
          {/* Блок для хлебных крошек */}
          <nav aria-label="Хлебные крошки" className="hidden md:block container mx-auto px-4 py-2">
            {/* Добавьте компонент Breadcrumbs */}
          </nav>
        </main>
      </body>
    </html>
  );
}